### ISSUE TITLE
🐛 [BUG] - Erreur de generation jinja à la première installation du rôle dso-console

### ISSUE THREAD

**Issue by rouja** [dnum-mi/dso-socle#255]
### Description

Il y a un problème dans le rôle dso-console. Dans le main.yaml, on fait : 
```
- name: Get pg-cluster-console-app secret
  kubernetes.core.k8s_info:
    namespace: "{{ dsc.console.namespace }}"
    kind: Secret
    name: pg-cluster-console-app
  register: pg_db_secret
```
Sauf qu'à ce moment là, sur une fresh install le secret n'existe pas. Je crois qu'il n'est crée qu'une fois qu'on déploie l'application argocd avec : 

```
- name: Apply app
  kubernetes.core.k8s:
    template: app.yaml.j2
```
Et du coup là tache du combine échoue car dans "values/00-main.j2" il est impossible de faire le rendu suivant : 
```
    dbUrl: {{ (pg_db_secret | from_yaml | json_query('resources[0].data.uri') | b64decode + '?schema=public') | default('postgresql://username:password@host:port?schema=public') }}
```

### Etapes de reproduction

```bash
1. Lancer l'installation sur un k8s vierge
2. Constater l'erreur
```

### Définition du fini

- [X] Le correctif est terminé
