### ISSUE TITLE
🐛 [BUG] - Fix CNPG backup on PAX

### ISSUE THREAD

**Issue by Falltrades** [dnum-mi/dso-socle#596]
### Description

No more wals archive pushed to s3 bucket since :
![Image](https://github.com/user-attachments/assets/8106780e-3251-45fb-bc46-f39164785d95)

**Comment by iliesmrf** [comment]
Peut etre penser à une sonde en sup pour vérifier la bonne exécution des Backup (en + de la resolution du bug)

**Comment by Falltrades** [comment]
L'erreur apparente :
`{"level":"info","ts":"2025-05-29T08:43:06.47169615Z","logger":"barman-cloud-check-wal-archive","msg":"2025-05-29 08:43:06,471 [43804] ERROR: WAL archive check failed for server pg-cluster-keycloak: Expected empty archive","pipe":"stderr","logging_pod":"pg-cluster-keycloak-2"}`

Les backups sont en succès après un 
`s3cmd rm s3://<endpoint>/cnpg/pg-cluster-keycloak/ --recursive`

![Image](https://github.com/user-attachments/assets/fb77169e-c5dc-487a-b654-820992314fe8)

Edit (2025-06-10): possible root cause = cloud provider migration.

**Comment by Falltrades** [comment]
Nettoyage des backups en erreur.
```shell
kubectl get backup -A | egrep 'failed|walArchivingFailing' | while read line; do
  backup_name=$(echo $line | awk '{print $2}' ) \
  name_space=$(echo $line | awk '{print $1}' ); \
  kubectl delete backup $backup_name -n $name_space
done

```
Vider le bucket s3.
```shell
s3cmd rm -r s3://<endpoint>/cnpg/
```

Se positionner sur le bon namespace puis scale down les replicas pour vider les pvc wal.
```shell
kubectl patch cluster $(kubectl get cluster | grep -v NAME | awk '{print $1}') --type=merge -p '{"spec":{"instances":1}}'
```

Si un des pvc wal est full, il faut désactiver la réconciliation.
```shell
kubectl annotate cluster  $(kubectl get cluster | grep -v NAME | awk '{print $1}') cnpg.io/reconciliationLoop=disabled --overwrite
```

Puis après avoir supprimer le pod et les pvc concernés (ne surtout pas toucher au primary), réactiver la réconciliation.
```shell
kubectl annotate cluster  $(kubectl get cluster | grep -v NAME | awk '{print $1}') cnpg.io/reconciliationLoop="" --overwrite
```

Remettre le bon nombre de replicas
```shell
kubectl patch cluster $(kubectl get cluster | grep -v NAME | awk '{print $1}') --type=merge -p '{"spec":{"instances":3}}'
```

**Comment by Falltrades** [comment]
Certains services ont une configuration incorrecte avec un mix de type `virtualHostStyle` + `pathStyle `  :

```
destinationPath: s3://<path>/cnpg
endpointURL: https://<path>.<endpoint>
```
Il a donc fallu corriger en configuration  `pathStyle ` pour que le backup fonctionne  :
```
destinationPath: s3://<path>/cnpg
endpointURL: https://<endpoint>
```

Pour la console, nous avions la configuration incorrecte suivante :
```yaml
  backup:
    barmanObjectStore:
      data:
        compression: gzip
      destinationPath: s3://<path>/cnpg
      endpointCA:                                                                                                                               
        key: ""
        name: ""
      endpointURL: https://<path>.<endpoint>
```
qu'il faudra corriger en (sans valeurs vides) :
```yaml
  backup:
    barmanObjectStore:
      data:
        compression: gzip
      destinationPath: s3://<path>/cnpg
      endpointURL: https://<endpoint>
```
